In [2]:
# 1.Write a python program to print the numpy array of size 3*4 containing all the values as 1.

import numpy as np

a = np.ones((3,4), dtype='int32')

In [3]:
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [4]:
# 2. Create a numpy array using inbuilt function and reshape it.

b = a.reshape(4,3)

In [5]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
c = a.reshape(2,6)

In [7]:
c

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
# 3. Write a python program to flatten a numpy array.

flatt = c.flatten()

In [9]:
flatt

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
flatt.shape

(12,)

In [11]:
# 4. What is the Transpose function in numpy used for?

# transpose useto convert any array or matrix into their row and colmn inter changed
arr1 = np.array([[1,2,3,4,5],[6,5,4,3,2],[3,4,5,6,7]])

In [12]:
arr2 = arr1.transpose()

In [13]:
arr2

array([[1, 6, 3],
       [2, 5, 4],
       [3, 4, 5],
       [4, 3, 6],
       [5, 2, 7]])

In [14]:
arr1

array([[1, 2, 3, 4, 5],
       [6, 5, 4, 3, 2],
       [3, 4, 5, 6, 7]])

In [15]:
# 5. Create two numpy arrays and perform any three arithmetic operations on it.

  arr1 = np.array([[1,2,3,4,5],[6,5,4,3,2],[3,4,5,6,7]])
  arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [16]:
arr3 = np.add(arr1, arr2)

In [17]:
arr3

array([[ 2,  4,  6,  8, 10],
       [ 7,  7,  7,  7,  7],
       [ 4,  6,  8, 10, 12]])

In [19]:
arr3 = np.subtract(arr1,arr2)

In [20]:
arr3

array([[ 0,  0,  0,  0,  0],
       [ 5,  3,  1, -1, -3],
       [ 2,  2,  2,  2,  2]])

In [21]:
arr3 = 3*arr1

In [22]:
arr3

array([[ 3,  6,  9, 12, 15],
       [18, 15, 12,  9,  6],
       [ 9, 12, 15, 18, 21]])

In [23]:
arr3 = np.multiply(arr1, 3)

In [24]:
arr3

array([[ 3,  6,  9, 12, 15],
       [18, 15, 12,  9,  6],
       [ 9, 12, 15, 18, 21]])

In [26]:
# 6. Write a python program to create a numpy array and iterate over its elements.

arr1 = np.array([[1,2,3,4,5],[6,5,4,3,2],[3,4,5,6,7]])

In [27]:
for i in arr1:
  print(i)

[1 2 3 4 5]
[6 5 4 3 2]
[3 4 5 6 7]


In [28]:
for i in arr1:
  for j in i:
    print(j)

1
2
3
4
5
6
5
4
3
2
3
4
5
6
7


In [33]:
# also we have to fetching by index
for i in range(len(arr1)):
  print(arr1[i], i)


[1 2 3 4 5] 0
[6 5 4 3 2] 1
[3 4 5 6 7] 2


In [37]:
for i in range(len(arr1)):
  for j in range(len(arr1[i])):
    print(arr1[i][j], i, j)

1 0 0
2 0 1
3 0 2
4 0 3
5 0 4
6 1 0
5 1 1
4 1 2
3 1 3
2 1 4
3 2 0
4 2 1
5 2 2
6 2 3
7 2 4


In [38]:
# 7. Write a python program to join two arrays.

arr1 = np.array([[1,2,3,4,5],[6,5,4,3,2],[3,4,5,6,7]])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [50]:
arr3 = np.concatenate((arr1, arr2))
arr3

array([[1, 2, 3, 4, 5],
       [6, 5, 4, 3, 2],
       [3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [54]:
# 8. Write a python program to create sequence of evenly spaced values within an interval.


spaced_ar = np.linspace(1, 100, 10)
spaced_ar

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [59]:
# 9. Write a python program to print sum of two numpy arrays column-wise.

arr1 = np.array([[1,2,3,4,5],[6,5,4,3,2],[3,4,5,6,7]])

In [62]:
arr3 = arr1.sum(axis=1)

In [63]:
arr3

array([15, 20, 25])

In [74]:
# 10. What is the difference between numpy flatten and ravel functions?

# flatten in numpy used to create or convert any dimension array into one dimension array.


In [30]:
# 11.  Write a python program that prints the squares of numbers in a given list using lambda function.

lista = [1, 2, 3, 4, 5, 6]

# squa = map(lambda list1: np.square(list1))
squa = map(lambda list1: list1**2, lista)

In [31]:
squa_list = list(squa)
squa_list

[1, 4, 9, 16, 25, 36]

In [32]:
for i in squa_list:
  print(i)

1
4
9
16
25
36


In [12]:
# 12. Write a python program to illustrate the use of inheritance.

class Car:
  def __init__(self, model):
    self.model = model

  def speed():
    print("Its running speed average 70kmph")

In [13]:
class Nano(Car):
  def __init__(self, model, feature):
    super().__init__(model)
    self.feature = feature

  def color():
    ptint("Nano car has blue color")

  def info():
    print()

In [14]:
NanoA = Nano("TATA", "35, light")

In [16]:
NanoA.model

'TATA'

In [17]:
NanoA.feature

'35, light'